/*
 Navicat Premium Data Transfer

 Source Server         : localhost_3306
 Source Server Type    : MySQL
 Source Server Version : 100133
 Source Host           : localhost:3306
 Source Schema         : thesheep

 Target Server Type    : MySQL
 Target Server Version : 100133
 File Encoding         : 65001

 Date: 28/06/2018 14:21:34
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for account
-- ----------------------------
DROP TABLE IF EXISTS `account`;
CREATE TABLE `account`  (
  `Makh` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `Email` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `Password` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `Name` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Phone` int(14) NOT NULL,
  `DOB` date NOT NULL,
  `Address` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Gender` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `index` int(2) NOT NULL,
  PRIMARY KEY (`Makh`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of account
-- ----------------------------
INSERT INTO `account` VALUES ('TK01', 'vongtandung@gmail.com', 'dung2609', 'Vòng Tần Dũng', 123456789, '1997-08-03', '227 Nguyễn Văn cừ', 'Nam', 2);
INSERT INTO `account` VALUES ('TK02', 'tranngocnu@gmail.com', 'ngocnutamkinh', 'Trần Ngọc Nữ', 1234567891, '2000-01-02', '100 Nguyễn Trãi', 'Nữ', 1);
INSERT INTO `account` VALUES ('TK03', 'Vanthiteo@gmail.com', 'thiteothino', 'Văn Thị Tèo Nở', 2147483647, '1999-02-04', '228 Trần Hưng Đạo', 'Nữ', 0);

-- ----------------------------
-- Table structure for ctdh
-- ----------------------------
DROP TABLE IF EXISTS `ctdh`;
CREATE TABLE `ctdh`  (
  `Madh` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `Masp` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `Soluong` int(2) NULL DEFAULT NULL,
  `Gia` int(255) NULL DEFAULT NULL,
  `Tong` int(255) NULL DEFAULT NULL,
  PRIMARY KEY (`Madh`, `Masp`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of ctdh
-- ----------------------------
INSERT INTO `ctdh` VALUES ('', '', NULL, NULL, NULL);
INSERT INTO `ctdh` VALUES ('KH01', 'BL02', 1, 120000, 120000);
INSERT INTO `ctdh` VALUES ('KH02', 'VI01', 2, 125000, 250000);
INSERT INTO `ctdh` VALUES ('KH02', 'VL05', 1, 1560000, 1560000);
INSERT INTO `ctdh` VALUES ('KV01', 'TX02', 1, 260000, 260000);
INSERT INTO `ctdh` VALUES ('KV01', 'VL07', 1, 2650000, 2650000);

-- ----------------------------
-- Table structure for donhang
-- ----------------------------
DROP TABLE IF EXISTS `donhang`;
CREATE TABLE `donhang`  (
  `Madh` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `Tenkh` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Diachi` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Tonghd` int(255) NULL DEFAULT NULL,
  `Ngaylap` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `Danggiao` int(2) NULL DEFAULT NULL,
  `Dagiao` int(2) NULL DEFAULT NULL,
  `Email` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  PRIMARY KEY (`Madh`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of donhang
-- ----------------------------
INSERT INTO `donhang` VALUES ('KH01', 'Lê Thị Na', '123/5/6/8 Nguyễn Văn Thanh', 380000, '2018-06-01', 1, 0, NULL);
INSERT INTO `donhang` VALUES ('KH02', 'Nguyễn Thị Tèo', '200 Nguyễn văn trỗi', 1810000, '2018-06-12', 0, 0, NULL);
INSERT INTO `donhang` VALUES ('VIP01', 'Tần Dũng Vòng', '100Too hiến thành', 2910000, '2018-06-29', 1, 1, NULL);

-- ----------------------------
-- Table structure for sanpham
-- ----------------------------
DROP TABLE IF EXISTS `sanpham`;
CREATE TABLE `sanpham`  (
  `Masp` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `Ten` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Loai` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Nhasx` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Gia` int(255) NULL DEFAULT NULL,
  `Xem` int(255) NULL DEFAULT NULL,
  `Mua` int(255) NULL DEFAULT NULL,
  `Anh` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Chitiet` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Xuatsu` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Gioi` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `STT` int(11) NOT NULL AUTO_INCREMENT,
  `Soluongton` int(255) NULL DEFAULT NULL,
  PRIMARY KEY (`STT`, `Masp`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 57 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of sanpham
-- ----------------------------
INSERT INTO `sanpham` VALUES ('', NULL, NULL, NULL, NULL, NULL, NULL, '43', NULL, NULL, NULL, 0, NULL);
INSERT INTO `sanpham` VALUES ('BL01', 'Balo SheepShop Hara120', 'Balo', 'Lazada', 100000, 160, 10, '1', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Thiết kế hiện đại; tiện dụng</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Chất liệu chuyên dụng cao cấp</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Phối đồ đa phong cách</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Đường may tỉ mỉ; chắc chắn</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Unnisex', 1, 20);
INSERT INTO `sanpham` VALUES ('BL02', 'Balo SheepShop Hara90', 'Balo', 'Lazada', 120000, 150, 3, '2', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Chất liệu cao cấp</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Thiết kế trẻ trung</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Đường may tỉ mỉ</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Unnisex', 2, 20);
INSERT INTO `sanpham` VALUES ('BL03', 'Balo SheepShop Hara150', 'Balo', 'Tiki', 130000, 360, 10, '3', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Chất liệu cao cấp</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Thiết kế trẻ trung</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Kiểu dáng thanh lịch</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Đường may tinh tế sắc sảo</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Hàn Quốc', 'Men', 3, 20);
INSERT INTO `sanpham` VALUES ('BL04', 'Balo Sheep Shop Hara170', 'Balo', 'Tiki', 145000, 350, 6, '4', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Dễ sử dụng</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Đường may chắc chắn; thiết kế thời trang</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Ngăn chứa tiện dụng</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Nhật Bản', 'Men', 4, 20);
INSERT INTO `sanpham` VALUES ('BL05', 'Balo SheepShop Hara156', 'Balo', 'Bitit', 150000, 450, 7, '5', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Chất liệu cao cấp</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Thiết kế trẻ trung</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Đường may tỉ mỉ</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Men', 5, 20);
INSERT INTO `sanpham` VALUES ('BL06', 'Balo SheepShop Hara 134', 'Balo', 'Bitit', 165000, 570, 6, '6', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Thiết kế tiện dụng , rộng rãi</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Chất liệu vai canvas cao cấp phố da thời thượng</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Kiểu dáng đa phong cách dễ dàng phối đồ</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Kích thước cao 46cm x dài 31cm x rộng 15 cm</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Men', 6, 20);
INSERT INTO `sanpham` VALUES ('BL07', 'Balo SheepShop Hara122', 'Balo', 'Adidas', 135000, 650, 8, '7', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Kích thước sản phẩm: 46cm x 30cm x 14cm</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Trọng lượng nhẹ, thích hợp cho việc di chuyển dễ dàng</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Phù hợp đi chơi, đi làm, đi học, hoặc đi du lịch</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Kiểu dáng cực đẹp, mẫu hot nhất năm 2018</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Unnisex', 7, 20);
INSERT INTO `sanpham` VALUES ('BL08', 'Balo SheepShop Hara135', 'Balo', 'Adidas', 142000, 570, 7, '8', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Dễ sử dụng</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Đường may chắc chắn; thiết kế thời trang</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Ngăn chứa tiện dụng</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Unnisex', 8, 20);
INSERT INTO `sanpham` VALUES ('BL09', 'Balo SheepShop Hara166', 'Balo', 'Nike', 164000, 580, 10, '9', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Chất liệu cotton</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Thiết kế trẻ trung</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Kiểu dáng thanh lịch</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Đường may tinh tế sắc sảo</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Men', 9, 20);
INSERT INTO `sanpham` VALUES ('BL10', 'Balo SheepShop Hara125', 'Balo', 'Nike', 147000, 650, 12, '10', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Chất liệu: Da Pu</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Thiết kế tiện dụng</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Kiểu dáng đa phong cách</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Ngăn chứa tiện lợi Note : Một số chi tiết trên sản phẩm có thể thay đổi tùy đợt sản xuât</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Nhật Bản', 'Men', 10, 20);
INSERT INTO `sanpham` VALUES ('TX01', 'Túi xách SheepShop Hono122', 'Tuixach', 'Lazada', 250000, 750, 8, '11', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Chất liệu cao cấp</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Thiết kế trẻ trung</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Đường may tỉ mỉ</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Trung Quốc', 'Unnisex', 11, 20);
INSERT INTO `sanpham` VALUES ('TX02', 'Túi xách SheepShop Hono135', 'Tuixach', 'Lazada', 260000, 450, 3, '12', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Mẫu túi đeo chéo mới nhất 2018 của Hàn Quốc form cứng</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Chất liệu: Da PU nhập khẩu Hàn Quốc</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Rộng 25 cm x sâu 7 cm x cao 15 cm</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Túi được thiết kế thời trang, sang trọng cho các bạn nữ</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Women', 12, 20);
INSERT INTO `sanpham` VALUES ('TX03', 'Túi xách SheepShop Hono147', 'Tuixach', 'Tiki', 275000, 550, 5, '13', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Chất liệu cotton</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Thiết kế trẻ trung</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Kiểu dáng thanh lịch</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Đường may tinh tế sắc sảo</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Women', 13, 20);
INSERT INTO `sanpham` VALUES ('TX04', 'Túi xách SheepShop Hono365', 'Tuixach', 'Tiki', 265000, 560, 7, '14', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Phong Cách Độc Lạ Ấn Tượng</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Chất Vải Bền Đẹp Cho Giá Trị Sử Dụng Lâu Dài.</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Thích Hợp mọi hoàn cảnh</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Thiết Kế Thời Trang Cao Cấp</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Trung Quốc', 'Women', 14, 20);
INSERT INTO `sanpham` VALUES ('TX05', 'Túi xách SheepShop Hono357', 'Tuixach', 'Bitit', 295000, 750, 14, '15', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Chất liệu cotton</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Thiết kế trẻ trung</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Kiểu dáng thanh lịch</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Đường may tinh tế sắc sảo</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Trung Quốc', 'Women', 15, 20);
INSERT INTO `sanpham` VALUES ('TX06', 'Túi xách SheepShop Hono456', 'Tuixach', 'Bitit', 215000, 560, 3, '16', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Size: Túi Lớn 22x25cm, Túi Lỡ 18x22cm, Ví 8x18cm</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Chất Liệu: Da Mịn Trơn.</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Màu Sắc: Đen - Đỏ - Trắng - Xám - Hồng Phấn - Tím</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Thiết Kế Thời Trang Cao Cấp</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Women', 16, 20);
INSERT INTO `sanpham` VALUES ('TX07', 'Túi xách SheepShop Hono008', 'Tuixach', 'Adidas', 235000, 750, 15, '17', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Mẫu túi đeo chéo mới nhất 2018 của Hàn Quốc form cứng</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Chất liệu: Da PU nhập khẩu Hàn Quốc</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Rộng 20 cm x sâu 7 cm x cao 15 cm</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>TTúi được thiết kế thời trang, sang trọng cho các bạn nữ</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Nhật Bản', 'Women', 17, 20);
INSERT INTO `sanpham` VALUES ('TX08', 'Túi xách SheepShop Hono765', 'Tuixach', 'Adidas', 242000, 673, 5, '18', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Kích thước: 20x15x10 (cm)</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Đường may tinh tế sắc sảo</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Kiểu dáng đa phong cách</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>TTúi được thiết kế thời trang, sang trọng cho các bạn nữ</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Women', 18, 20);
INSERT INTO `sanpham` VALUES ('TX09', 'Túi xách SheepShop Hono568', 'Tuixach', 'Nike', 255000, 634, 8, '19', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Chất liệu lớp lót: Vải</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Đường may tinh tế sắc sảo</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Thiết kế chắc chắn</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Thương hiệu: Thương hiệu độc quyền</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Women', 19, 20);
INSERT INTO `sanpham` VALUES ('TX10', 'Túi xách SheepShop Hono698', 'Tuixach', 'Nike', 265000, 365, 2, '20', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Mẫu bán chạy nhất , thích hợp công sở, đi chơi</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Chất liệu Da cao cấp, đừong may tỉ mĩ, tinh tế.</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Thiết kế thời trang; trẻ trung; trang nhã và lịch sự.</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Độ bền cao</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Women', 20, 20);
INSERT INTO `sanpham` VALUES ('VI01', 'Ví Sheep Shop Furedani007', 'Vi', 'Lazada', 125000, 265, 3, '21', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Thiết Kế Gọn Nhẹ Và Mỏng với kích thước 12*9*1.5cm</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Đứng Ví KHÔNG Làm Gấp Nếp Tiền</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Chứa Được 50 Tờ Tiền Và 5 Thẻ ATM mà Không Tài Nào Rớt Ra</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Phù Hợp với Mọi Lứa Tuổi Sử Dụng, những Người Yêu Sự Tối Giản</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Trung Quốc', 'Men', 21, 20);
INSERT INTO `sanpham` VALUES ('VI02', 'Ví Sheep Shop Furedani120', 'Vi', 'Lazada', 175000, 365, 4, '22', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Ngăn chứa tiện lợi</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Đứng Ví KHÔNG Làm Gấp Nếp Tiền</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Chất liệu da cao cấp.</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Phù Hợp với Mọi Lứa Tuổi Sử Dụng, những Người Yêu Sự Tối Giản</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Men', 22, 20);
INSERT INTO `sanpham` VALUES ('VI03', 'Ví Sheep Shop Furedani330', 'Vi', 'Tiki', 156000, 640, 8, '23', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Chất liệu da bò 100% mềm mại</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Đứng Ví KHÔNG Làm Gấp Nếp Tiền</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Tích hợp nhiềungăn gọn gàng.</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Kiểu dáng sang trọng, lịch lãm.</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Nhật Bản', 'Men', 23, 20);
INSERT INTO `sanpham` VALUES ('VI04', 'Ví Sheep Shop Furedani550', 'Vi', 'Tiki', 145000, 560, 4, '24', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Nhiều ngănKích thước: 19 * 2 * 11 cm</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Phong cách Hàn Quốc</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Tích hợp nhiềungăn gọn gàng.</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Chất liệu cao cấp</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Hàn Quốc', 'Men', 24, 20);
INSERT INTO `sanpham` VALUES ('VI05', 'Ví Sheep Shop Furedani680', 'Vi', 'Bitit', 125000, 570, 6, '25', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Chất liệu Da cá sấu</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Kiểm tra hàng trước khi nhận</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Phong cách độc lạ</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Nhiều ngăn, không nhăn tiền</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Men', 25, 20);
INSERT INTO `sanpham` VALUES ('VI06', 'Ví Sheep Shop Furedani935', 'Vi', 'Bitit', 126000, 580, 4, '26', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Thiết kế nhỏ gọn, thời trang, xinh xắn.</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Thích hợp sử dụng thường xuyên.</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Kiểu dáng đơn giản dễ sử dụng.</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Đường may tỉ mỉ, tạo form ví đẹp mắt.</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Trung Quốc', 'Women', 26, 20);
INSERT INTO `sanpham` VALUES ('VI07', 'Ví Sheep Shop Furedani778', 'Vi', 'Adidas', 285000, 590, 5, '27', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Ví cầm tay nhiều ngăn có thiết kế nhỏ gọn, tinh tế,</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Chất liệu bền đẹp giúp bạn dễ dàng mang theo những vật dụng cá nhân bên mình.</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>KMàu sắc đẹp mắt, có thể mix nhiều trang phục.</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Đường may tỉ mỉ, tạo form ví đẹp mắt.</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Women', 27, 20);
INSERT INTO `sanpham` VALUES ('VI08', 'Ví Sheep Shop Furedani145', 'Vi', 'Adidas', 136000, 450, 3, '28', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Kích thước lớn: 18x11cm. Chứa được smartphone 5.5\" (iPhone 6,7 plus)​​​​​</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>100% nguyên vật liệu thân thiện với môi trường.</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Không phai màu, không dễ biến dạng khi bị thấm nước.</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Chất liệu: Vải dạ - loại dày và cứng - Chống xước. Đường chỉ chắc chắn.</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Women', 28, 20);
INSERT INTO `sanpham` VALUES ('VI09', 'Ví Sheep Shop Furedani236', 'Vi', 'Nike', 126000, 480, 6, '29', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Kích thước lớn: 18x11cm​​​​​</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Màu Hồng nữ tính</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Không phai màu, không dễ biến dạng khi bị thấm nước.</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Phong cách trẻ trung</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Hàn Quốc', 'Women', 29, 20);
INSERT INTO `sanpham` VALUES ('VI10', 'Ví Sheep Shop Furedani146', 'Vi', 'Nike', 169000, 179, 3, '30', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Da bò thật 100%</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Thiết kế tinh tế</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Chống thấm nước</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Sản phẩm bền và chất lượng</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Trung Quốc', 'Women', 30, 20);
INSERT INTO `sanpham` VALUES ('VL01', 'Vali Sheep Shop DL05', 'Vali', 'Lazada', 1750000, 650, 3, '31', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Ngăn chứa lớn, tiện dụng cho bạn có nhều không gian chứa các loại vật dụng cá nhân khi du lịch.</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Túi bằng chất liệu vải cao cấp bền đẹp, chống thấm nước, giúp bạn luôn yên tâm khi sử dụng nếu có lỡ gặp trời mưa khi đang đi ngoài đường.</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Chất liệu dày dặn, bền đẹp, thời gian sử dụng lâu dài.</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Bánh xe phần dưới xoay chắc chắn, không mất sức nhiều cho người dùng.</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Mỹ', 'Unnisex', 31, 20);
INSERT INTO `sanpham` VALUES ('VL02', 'Vali Sheep Shop DL13\r\n', 'Vali', 'Lazada', 2150000, 670, 2, '32', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Chất liệu : Vải polyester siêu nhẹ</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Thích hợp đi du lịch gia đình</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Cần kéo và bánh xe chắc chắn</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Bảo hành 12 tháng</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Unnisex', 32, 20);
INSERT INTO `sanpham` VALUES ('VL03', 'Vali Sheep Shop DL120', 'Vali', 'Tiki', 1685000, 780, 4, '33', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Khóa số : Bảo mật 3 số khóa CMI (bảo mật cao) đổi mật mã theo ý muốn.</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Kích thước: size 20 inch 50cm*35cm*20cm.(đi du lịch khoảng 2-3 ngày-2 người. 3-4 ngày 1 người.)</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Tay kéo, hợp kim không ghỉ có thể rút ra và đóng vào một cách trơn tru, dễ dàng.</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Kích thước: size 24 inch 60cm*40cm*24cm.(đi du lịch khoảng 1 tuần-1 người. 3-4 ngày-gia đình. </p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Unnisex', 33, 20);
INSERT INTO `sanpham` VALUES ('VL04', 'Vali Sheep Shop DL365', 'Vali', 'Tiki', 1768000, 640, 6, '34', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Chất liệu : Vải polyester siêu nhẹ</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Cần kéo và bánh xe chắc chắn</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Thích hợp đi du lịch gia đình</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Bảo hành 12 tháng</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Unnisex', 34, 20);
INSERT INTO `sanpham` VALUES ('VL05', 'Vali Sheep Shop DL457', 'Vali', 'Bitit', 1560000, 750, 4, '35', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Túi thích hợp dùng khi đi công tác, du lịch.</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Ngăn chứa lớn, tiện dụng cho bạn có nhều không gian chứa các loại vật dụng cá nhân khi du lịch.</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Túi bằng chất liệu vải cao cấp bền đẹp, chống thấm nước, giúp bạn luôn yên tâm khi sử dụng nếu có lỡ gặp trời mưa khi đang đi ngoài đường.</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Thiết kế quai xách tiện lợi, có cần kéo và 2 bánh xe chắc chắn giúp di chuyển dễ dàng.</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Mỹ', 'Unnisex', 35, 20);
INSERT INTO `sanpham` VALUES ('VL06', 'Vali Sheep Shop DL693', 'Vali', 'Bitit', 1456000, 870, 6, '36', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Vali kéo du lịch họa tiết cánh bướm size 24 inch</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Kích thước: 24 inch: 24:65x40x25 cm ( đựng 17-25kg)</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Bên ngoài là nhựa ABS cực bền, bên trong là vải chống thấm</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Bên dưới là bộ bốn bánh xe xoay 360 độ đa hướng ziczac, rất nhẹ nhàng và linh hoạt khi di chuyển.</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Mỹ', 'Unnisex', 36, 20);
INSERT INTO `sanpham` VALUES ('VL07', 'Vali Sheep Shop DL235', 'Vali', 'Adidas', 2650000, 890, 3, '37', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Phong cách sang trọng, thích hợp đi du lịch</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Túi du lịch cần kéo 3176 có kích thước : Ngang 52 x Cao 30 x Rộng 26 cm</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Trọng lượng siêu nhẹ : 1.8 Kg</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Dễ dàng di chuyể</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Unnisex', 37, 20);
INSERT INTO `sanpham` VALUES ('VL08', 'Vali Sheep Shop DL152', 'Vali', 'Adidas', 2568000, 560, 2, '38', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Phong cách sang trọng, thích hợp đi du lịch</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Cần kéo nhôm hợp kim cứng cáp</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Chất liệu: vải dù cao cấp, simili giả da.</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Chống thấm nước</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Nhật Bản', 'Unnisex', 38, 20);
INSERT INTO `sanpham` VALUES ('VL09', 'Vali Sheep Shop DL320', 'Vali', 'Nike', 1450000, 650, 10, '39', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Kích thước 20in (50cm x 36cm x 24,4cm)</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Sản phẩm được làm từ Polycarbonate với màu trắng tinh khiết</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Phù hợp với tất cả lứa tuổi</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Chống thấm nước</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Mỹ', 'Unnisex', 39, 20);
INSERT INTO `sanpham` VALUES ('VL10', 'Vali Sheep Shop DL610', 'Vali', 'Nike', 1356000, 750, 3, '40', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Chất liệu: Vải dù, nhựa, nhôm.- Kích thước: (D x R x C): 34 x 23 x 53(cm)</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Size xách tay 20 in của các hãng hàng không giá rẻ</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Trọng lượng : 2.7kg. Màu sắc: đen có logo Tiger phía trước</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p> Cần kéo bằng nhôm, bánh xe xoay 360 độ, có cả quai xách ngang và dọc</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Unnisex', 40, 20);
INSERT INTO `sanpham` VALUES ('BL11', 'Balo SheepShop Hara368', 'Balo', 'Adidas', 260000, 850, 4, '41', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Kiểu dáng thời trang mạnh mẽ ^^!</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Chất da: PU cao cấp</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Độ bền cao màu da đẹp</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Độ bền cao màu da đẹp</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Hàn Quốc', 'Unnisex', 41, 20);
INSERT INTO `sanpham` VALUES ('BL12', 'Balo SheepShop Hara004', 'Balo', 'Tiki', 256000, 450, 6, '42', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Thiết kế hiện đại, kiểu dáng thời trang</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Chất liệu vải cao cấp, bền đẹp</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Đường chỉ may chắc chắn</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Kích thước 42cm x 12cm x 30cm</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Unnisex', 42, 20);
INSERT INTO `sanpham` VALUES ('TX11', 'Túi xách SheepShop Hono148', 'Tuixach', 'Tiki', 140000, 570, 20, '44', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Kích thước: 20x15x10 (cm)</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Đường may tinh tế sắc sảo</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Kiểu dáng đa phong cách</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>TTúi được thiết kế thời trang, sang trọng cho các bạn nữ</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Women', 44, 20);
INSERT INTO `sanpham` VALUES ('BL13', 'Balo SheepShop Hara143', 'Balo', 'Bitit', 178000, 470, 3, '45', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Thiết kế hiện đại, kiểu dáng thời trang</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Giao Hàng toàn quốc, thanh toán khi nhận hàng</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Lót trong chất liệu vải với đường may chắc chắn.</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Kích Thước:Dài 21cm x Rộng 12cm x Cao 26cm</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Thái Lan', 'Women', 45, 20);
INSERT INTO `sanpham` VALUES ('BL14', 'Balo SheepShop Hara126', 'Balo', 'Lazada', 97000, 740, 21, '46', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Balo công chúa đáng yêu</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Kích thước túi: Khoảng 27 x 21 x 8cm</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Độ tuổi: Cho các bé 1-3 tuổi</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Với balo công chúa đáng yêu các mẹ có thể bỏ những đồ dùng cần thiết cho trẻ nhỏ như đồ chơi, đồ ăn hoa quả, sách nhỏ, bút mực, vv.</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Kid', 46, 20);
INSERT INTO `sanpham` VALUES ('BL15', 'Balo Sheep Shop Hara127', 'Balo', 'Tiki', 85000, 560, 15, '47', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Balo Kitty đáng yêu</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Độ tuổi: Cho các bé 1-3 tuổi</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Kích thước túi: Khoảng 23 x 7 x 27cm</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Phong cách thời trang, trọng lượng nhẹ, mềm mại và nhiều màu sắc</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Kid', 47, 20);
INSERT INTO `sanpham` VALUES ('BL16', 'Balo  SheepShop Hara980', 'Balo', 'Adidas', 86000, 546, 12, '48', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Ba lô hình thú chất liệu nhung cao cấp,nhẹ, được làm 3 lớp dày dặn, bền đẹp, phù hợp cho bé từ 2 đến 6 tuổi</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Sản phẩm có 1 ngăn chính; 1 ngăn phụ. Bên trong rộng rãi bé có thể đựng quần áo, sữa, bỉm và 1 vài đồ chơi nho nhỏ.</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Kích thước túi: Khoảng 23 x 7 x 27cm</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Hình dáng ngộ nghĩnh sinh động</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Kid', 48, 20);
INSERT INTO `sanpham` VALUES ('BL17', 'Balo SheepShop Hara982', 'Balo', 'Bitit', 79000, 490, 20, '49', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Thiết kế khoa học chống gù lưng ở trẻ em </p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Nhẹ nhàng , khoang chứa rộng rãi, vải chống thấm nước.</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Kích thước: cao  38x dài 28 x rộng 20 cm</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Sử dụng sản phẩm cho nhiều năm học liên tục</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Kid', 49, 20);
INSERT INTO `sanpham` VALUES ('BL18', 'Balo SheepShop Hara983', 'Balo', 'Nike', 75000, 450, 12, '50', '<div class=\"row\">\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Phù hợp cho trẻ nam và nữ từ 2- 6 tuổi.</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Chất liệu làm bằng vải chống thấm 2 lớp</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                                <div class=\"col-md-4\">\r\n                                    <ul>\r\n                                        <li>\r\n                                            <p>Kích thước;32cm x 27cm x 11cm</p>\r\n                                        </li>\r\n                                        <li>\r\n                                            <p>Quai đeo to 6cm không bị đau khi đeo, có thể điều chỉnh độ dài ngắn</p>\r\n                                        </li>\r\n                                    </ul>\r\n                                </div>\r\n                            </div>', 'Việt Nam', 'Kid', 50, 20);

-- ----------------------------
-- Table structure for sessions
-- ----------------------------
DROP TABLE IF EXISTS `sessions`;
CREATE TABLE `sessions`  (
  `session_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `expires` int(11) UNSIGNED NOT NULL,
  `data` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  PRIMARY KEY (`session_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of sessions
-- ----------------------------
INSERT INTO `sessions` VALUES ('CMILj0yXb9FwisswfiruykjkpBCHf1X1', 1530164793, '{\"cookie\":{\"originalMaxAge\":null,\"expires\":null,\"httpOnly\":true,\"path\":\"/\"},\"isLogged\":false}');
INSERT INTO `sessions` VALUES ('gPhm6LjfCUvrODfERPHg2WoNS4JtwDv1', 1530162622, '{\"cookie\":{\"originalMaxAge\":null,\"expires\":null,\"httpOnly\":true,\"path\":\"/\"},\"isLogged\":false}');

SET FOREIGN_KEY_CHECKS = 1;
